name: Build, Publish Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mtaste_frontend:latest

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./Mtaste
    - name: Build the project
      run: npm run build
      working-directory: ./Mtaste
 
    - name: Archive production artifacts
      run: ls Mtaste && pwd&&tar -czf dist.tar.gz -C Mtaste/dist .
      working-directory: .

    
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "dist.tar.gz"
        target: " /var/www/${{ secrets.SSH_USERNAME }}/data/www/dist.tar.gz"

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ./www
          # Remove old files
          rm -rf /var/www/${{ secrets.SSH_USERNAME }}/data/www/mtaste.ru/*
          # Extract the new files
          ls
          pwd

          tar -xzf ~/dist.tar.gz -C /var/www/${{ secrets.SSH_USERNAME }}/data/www/mtaste.ru/
          # Cleanup
          rm ~/dist.tar.gz
