name: Build, Publish Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mtaste_frontend:latest

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }} 
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Remove the old repository if it exists
          rm -rf ~/repo
          # Clone the repository
          git clone https://github.com/Cibus65/MtasteFront-end.git ~/repo
          cd ~/repo
          cd ./MtasteFront-end/Mtaste
          rm .env
          echo "VITE_BASE_URL=http://${{secrets.BACKEND_IP}}:8082" > .env
          # Install dependencies and build the project
          npm install
          npm run build
          # Move built files to the www directory
          rm -rf /var/www/${{ secrets.SSH_USERNAME }}/data/data/www/mtaste.ru/
          cp -r dist/* /var/www/${{ secrets.SSH_USERNAME }}/data/data/www/mtaste.ru/
